### ISSUE TITLE
Unable to reset a user password

### ISSUE THREAD

**Issue by tompscanlan** [OpenMeet-Team/openmeet-api#160]
![image](https://github.com/user-attachments/assets/e59e3b09-83b7-4ebc-8868-fd3042dc897d)

API error log:
```
openmeet-api
[31m[Nest] 19 - [39m11/29/2024, 3:48:35 AM [31m ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31m385B27D0197F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
openmeet-api
[39m
openmeet-api
Error: 385B27D0197F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
```

**Comment by tompscanlan** [comment]
user and password are set in the `secrets.env` file, not in the configmap. I think they are correct, but I'll go try to verify that.

You think that's the mail sending causing the error?  Could it be a zulip connection instead?

**Comment by stanislavkhatko** [comment]
Checked logs as well. It's related to ssl on mail sending. I've faced it too when sending MAIL_IGNORE_TLS=false. In this case it's not ignoring ssl but throwing exception instead.

**Comment by tompscanlan** [comment]
Mail sends now, but we arrive at:

    https://platform.openmeet.net/auth/password-change?hash=hashstring&expires=1732911812499#/
    
With no request to set a new password.

We should be prompted to reset the password and use the auth api to make it so.  Now I think this is a problem in platform, but keeping here because I don't know how to move it :)

**Comment by stanislavkhatko** [comment]
Ok, if shouldn't be there. I'll move to properly set tenant config as we should pass tenant config 'frontendDomain' instead. Will keep updated the issue
